### ISSUE TITLE
max (max) steps - 50,000

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine.py#51]
What if a person specifies 10,000,000 steps?  Let's have a realistic limit.   50,000 is good enough - 20,000 is the "normal" max steps.

**Comment by mshannon-sil** [comment]
@johnml1135 If the user specifies a number of steps larger than the max amount of steps, should we fail the job and give them a chance to reenter a max steps that is under the limit? Or should we just automatically change it to the upper limit of 50000 while logging a warning without failing? The second option would be a smoother experience, although it wouldn't be as transparent to the user since I'm not sure that users will be able to see warning logs in machine.py.

**Comment by ddaspit** [comment]
We should throw an error if they are over the limit.
